import os

## Database
SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")

## API ##
SOCRATA_TOKEN = os.getenv("SOCRATA_TOKEN")
SOCRATA_USERNAME = os.getenv("SOCRATA_USERNAME")
SOCRATA_PASSWORD = os.getenv("SOCRATA_PASSWORD")