data:
  import_places_api: 
    url: chronicdata.cdc.gov
    dataset_identifier: cwsq-ngmh
    attempts: 4
model:
  name: linear-regression
  author: Jason Summer
  version: AA1
  description: Predicts the log-odds of the proportion of county population with poor health based on proportional demographics.
  tags:
    - regression
    - health
    - population health
transform_data:
  import_file:
    columns: [StateDesc, CountyName, CountyFIPS, LocationID, TotalPopulation, Geolocation, MeasureId, Data_Value, Category, Short_Question_Text, Measure]
  validate_df:
    cols: 
      StateDesc: str
      CountyName: str
      CountyFIPS: int
      LocationID: int
      TotalPopulation: int
      Geolocation: str
      MeasureId: str
      Data_Value: float
  prep_data:
    response: GHLTH
    invalid_measures: [TEETHLOST, SLEEP, MAMMOUSE, DENTAL, COREW, COREM, COLON_SCREEN, CERVICAL, LPA, MHLTH, PHLTH]
    make_floats: [ACCESS2, ARTHRITIS, BINGE, BPHIGH, BPMED, CANCER, CASTHMA, CHD, CHECKUP, CHOLSCREEN, COPD, CSMOKING, DEPRESSION, DIABETES, GHLTH, HIGHCHOL, KIDNEY, OBESITY, STROKE]
    make_logit: GHLTH
  scale_values:
    columns: TotalPopulation
  one_hot_encode:
    states_region: True 
train_test_split:
  test_size: 0.3
  random_state: 42
train_model:
  features: [ACCESS2, ARTHRITIS, BINGE, BPHIGH, BPMED, CANCER, CASTHMA, CHD, CHECKUP, CHOLSCREEN, COPD, CSMOKING, DEPRESSION, DIABETES, HIGHCHOL, KIDNEY, OBESITY, STROKE, scaled_TotalPopulation, Midwest, Northeast, South, Southwest]
  response: GHLTH
  validate_df:
    cols: 
      ACCESS2: float
      ARTHRITIS: float
      BINGE: float
      BPHIGH: float
      BPMED: float
      CANCER: float
      CASTHMA: float
      CHD: float
      CHECKUP: float
      CHOLSCREEN: float
      COPD: float
      CSMOKING: float
      DEPRESSION: float
      DIABETES: float
      HIGHCHOL: float
      KIDNEY: float
      OBESITY: float
      STROKE: float
      scaled_TotalPopulation: float
      Midwest: int
      Northeast: int
      South: int
      Southwest: int
  method: LinearRegression
  params:
     fit_intercept: True
score:
  validate_df:
    cols:
      ACCESS2: float
      ARTHRITIS: float
      BINGE: float
      BPHIGH: float
      BPMED: float
      CANCER: float
      CASTHMA: float
      CHD: float
      CHECKUP: float
      CHOLSCREEN: float
      COPD: float
      CSMOKING: float
      DEPRESSION: float
      DIABETES: float
      HIGHCHOL: float
      KIDNEY: float
      OBESITY: float
      STROKE: float
      scaled_TotalPopulation: float
      Midwest: int
      Northeast: int
      South: int
      Southwest: int
      training: int


